name: deploy

on:
    push:
    workflow_dispatch:
    # schedule:
    #     # Runs everyday at 8:00 AM
    #     - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "0.110.0"
            - name: submodule update
              run: git submodule update
              
            - name: Build Web
              run: hugo
              
            - name: Create dist directory
              run: mkdir -p /home/runner/work/run-blog/run-blog/dist
            - name: Build upload file
              run: hugo --source dist --baseURL https://blog.jysgdyc.com


                
            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONSDEPLOYKEY }}
                  EXTERNAL_REPOSITORY: sanbeiicecream/sanbeiicecream.github.io
                  PUBLISH_BRANCH: main
                  PUBLISH_DIR: ./public
                  commit_message: ${{ github.event.head_commit.message }}
            - name: Copy files to server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                port: ${{ secrets.KR_SSH_PORT }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.KR_SSH_PRIVATE_KEY }}
                source: ./dist/*
                target: /usr/share/blog/
